export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Стартовый',
    description: 'Для небольших кофеен',
    price: 15000,
    priceUnit: '₽',
    minQuantity: 1000,
    quantityUnit: 'шт',
    isPopular: false,
    features: [
      { text: 'Любой размер на выбор', included: true },
      { text: 'Стандартная упаковка', included: true },
      { text: 'Доставка в течение 5-7 дней', included: true },
      { text: 'Базовая поддержка', included: true },
      { text: 'Гарантия качества', included: true },
    ],
  },
  {
    id: 'business',
    name: 'Бизнес',
    description: 'Для растущего бизнеса',
    price: 40000,
    priceUnit: '₽',
    minQuantity: 5000,
    quantityUnit: 'шт',
    isPopular: true,
    badge: 'Популярный выбор',
    features: [
      { text: 'Все размеры в ассортименте', included: true },
      { text: 'Премиум упаковка', included: true },
      { text: 'Доставка в течение 3-5 дней', included: true },
      { text: 'Приоритетная поддержка', included: true },
      { text: 'Расширенная гарантия', included: true },
      { text: 'Скидка 10% на следующий заказ', included: true },
    ],
  },
  {
    id: 'corporate',
    name: 'Корпоративный',
    description: 'Для крупных сетей',
    price: null,
    priceLabel: 'По запросу',
    minQuantity: 20000,
    quantityUnit: 'шт',
    isPopular: false,
    features: [
      { text: 'Индивидуальный дизайн', included: true },
      { text: 'Брендирование логотипом', included: true },
      { text: 'Экспресс доставка 1-2 дня', included: true },
      { text: 'Персональный менеджер', included: true },
      { text: 'Максимальная гарантия', included: true },
      { text: 'Гибкие условия оплаты', included: true },
      { text: 'Специальные цены', included: true },
    ],
  },
];
