export const PRICING_PLANS = [
  {
    id: "starter",
    name: "Малый опт",
    description: "Для небольших кофеен",
    price: "От 10 000 шт",
    priceUnit: "",
    minQuantity: "",
    quantityUnit: "",
    isPopular: false,
    features: [
      { text: "175мл — 1.70₽", included: true },
      { text: "330мл — 3.20₽", included: true },
      { text: "250мл — 2.00₽", included: true },
      { text: "350мл — 2.50₽", included: true },
      { text: "450мл — 2.80₽", included: true },
    ],
  },
  {
    id: "business",
    name: "Опт",
    description: "Для растущего бизнеса",
    price: "Договорная",
    priceUnit: "",
    minQuantity: "от 100 000",
    quantityUnit: "шт",
    isPopular: true,
    badge: "Популярный выбор",
    features: [
      { text: "Все размеры в ассортименте", included: true },
      { text: "Премиум упаковка", included: true },
      { text: "Доставка в течение 3-5 дней", included: true },
      { text: "Приоритетная поддержка", included: true },
      { text: "Расширенная гарантия", included: true },
    ],
  },
  {
    id: "corporate",
    name: "Крупный опт",
    description: "Для крупных сетей",
    price: "Договорная",
    priceLabel: "По запросу",
    minQuantity: "от 500 000",
    quantityUnit: "шт",
    isPopular: false,
    features: [
      { text: "Индивидуальный дизайн", included: true },
      { text: "Брендирование логотипом", included: true },
      { text: "Экспресс доставка 1-2 дня", included: true },
      { text: "Персональный менеджер", included: true },
      { text: "Максимальная гарантия", included: true },
      { text: "Гибкие условия оплаты", included: true },
      { text: "Специальные цены", included: true },
    ],
  },
];
