export const PRODUCTS = [
  {
    id: 1,
    size: "175мл",
    name: "Эспрессо",
    description: "Идеально для эспрессо и ристретто",
    price: 2.5,
    priceUnit: "₽",
    dimensions: {
      diameter: 62,
      height: 65,
    },
    variants: [
      {
        id: "180-v1",
        name: "Белый",
        image: "/img/180.2.png",
        thumb: "/img/180.2.png",
        color: "#FFFFFF",
      },
      {
        id: "180-v2",
        name: "Крафт",
        image: "/img/180.1.png",
        thumb: "/img/180.1.png",
        color: "#C4A77D",
      },
      {
        id: "180-v3",
        name: "Чёрный",
        image: "/img/180.3.png",
        thumb: "/img/180.3.png",
        color: "#1E2235",
      },
    ],
  },
  {
    id: 2,
    size: "250мл",
    name: "Американо",
    description: "Классический размер для американо",
    price: 3.2,
    priceUnit: "₽",
    dimensions: {
      diameter: 80,
      height: 90,
    },
    variants: [
      {
        id: "250-v1",
        name: "Вариант 1",
        image: "/img/250.1.png",
        thumb: "/img/250.1.png",
        color: "#FFFFFF",
        customSize: {
          width: "250%",
          height: "200%",
          backgroundSize: "50%",
          backgroundPosition: "50% 10%",
        },
      },
      {
        id: "250-v2",
        name: "Вариант 2",

        image: "/img/250.9.png",
        thumb: "/img/250.9.png",
        isPattern: true,
        customSize: {
          width: "160%",
          height: "120%",
          backgroundSize: "75%",
          backgroundPosition: "50% 50%",
          noGradient: true,
        },
      },
      {
        id: "250-v3",
        name: "Вариант 3",

        image: "/img/black.png",
        thumb: "/img/black.png",
        color: "#C4A77D",
        customSize: {
          width: "110%",
          height: "110%",
          // backgroundSize: "60%",
          // backgroundPosition: "50% 70%",
        },
      },
      {
        id: "250-v4",
        name: "Вариант 4",
        image: "/img/250.10.png",
        thumb: "/img/250.10.png",
        isPattern: true,
        customSize: {
          width: "160%",
          height: "120%",
          backgroundSize: "75%",
          backgroundPosition: "50% 50%",
          noGradient: true,
        },
      },
      {
        id: "250-v5",
        name: "Вариант 5",
        image: "/img/250.5.png",
        thumb: "/img/250.5.png",
        color: "#E53935",
        customSize: {
          width: "120%",
          height: "80%",
          backgroundSize: "65%",
          backgroundPosition: "50% 50%",
          noGradient: true,
        },
      },
      {
        id: "250-v6",
        name: "Вариант 6",
        image: "/img/250.6.png",
        thumb: "/img/250.6.png",
        color: "#2196F3",
        customSize: {
          width: "150%",
          height: "110%",
          backgroundSize: "65%",
          backgroundPosition: "50% 70%",
          noGradient: true,
        },
      },
      {
        id: "250-v7",
        name: "Вариант 7",
        image: "/img/250.7.png",
        thumb: "/img/250.7.png",
        color: "#9C27B0",
        customSize: {
          width: "150%",
          height: "120%",
          backgroundSize: "55%",
          backgroundPosition: "50% 35%",
          noGradient: true,
        },
      },
      {
        id: "250-v8",
        name: "Вариант 8",
        image: "/img/250.8.png",
        thumb: "/img/250.8.png",
        isPattern: true,
        customSize: {
          width: "150%",
          height: "110%",
          backgroundSize: "65%",
          backgroundPosition: "50% 35%",
          noGradient: true,
        },
      },
      {
        id: "250-v9",
        name: "Вариант 9",
        // image: "/img/250.9.png",
        // thumb: "/img/250.9.png",
        // isPattern: true,
        // customSize: {
        //   width: "160%",
        //   height: "120%",
        //   backgroundSize: "75%",
        //   backgroundPosition: "50% 50%",
        //   noGradient: true,
        // },
        image: "/img/250.3.png",
        thumb: "/img/250.3.png",
        color: "#1E2235",
        customSize: {
          width: "200%",
          height: "180%",
          backgroundSize: "50%",
          backgroundPosition: "50% 10%",
        },
      },
      {
        id: "250-v10",
        name: "Вариант 10",

        image: "/img/250.4.png",
        thumb: "/img/250.4.png",
        color: "#1DB954",
        customSize: {
          width: "180%",
          height: "150%",
          backgroundSize: "50%",
          backgroundPosition: "50% 50%",
        },
      },
    ],
  },
  {
    id: 5,
    size: "300мл",
    name: "Новинка",
    description: "Скоро в продаже",
    price: 3.5,
    priceUnit: "₽",
    dimensions: {
      diameter: 85,
      height: 100,
    },
    isSkeleton: true,
    variants: [
      {
        id: "300-v1",
        name: "Скоро",
        image: null,
        thumb: null,
        color: "#E0E0E0",
      },
    ],
  },
  {
    id: 3,
    size: "350мл",
    name: "Латте",
    description: "Большой размер для латте и капучино",
    price: 3.8,
    priceUnit: "₽",
    dimensions: {
      diameter: 90,
      height: 110,
    },
    variants: [
      {
        id: "350-v4",
        name: "Вариант 4",
        image: "/img/350.4.png",
        thumb: "/img/350.4.png",
        isPattern: true,
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "60%",
          backgroundPosition: "50% 140%",
          noGradient: true,
        },
      },
      {
        id: "350-v5",
        name: "Вариант 5",
        image: "/img/black.png",
        thumb: "/img/black.png",
        isPattern: true,
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "60%",
          backgroundPosition: "50% 85%",
          noGradient: true,
        },
      },
      {
        id: "350-v6",
        name: "Вариант 6",
        image: "/img/brown.png",
        thumb: "/img/brown.png",
        isPattern: true,
        customSize: {
          width: "150%",
          height: "90%",
          backgroundSize: "70%",
          backgroundPosition: "50% 5%",
          noGradient: true,
        },
      },
      {
        id: "350-v1",
        name: "Вариант 1",
        image: "/img/350.1.png",
        thumb: "/img/350.1.png",
        color: "#FFFFFF",
      },
      {
        id: "350-v2",
        name: "Вариант 2",
        image: "/img/350.2.png",
        thumb: "/img/350.2.png",
        color: "#C4A77D",
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "65%",
          backgroundPosition: "50% 50%",
          noGradient: true,
        },
      },
      {
        id: "350-v3",
        name: "Вариант 3",
        image: "/img/350.3.png",
        thumb: "/img/350.3.png",
        color: "#1E2235",
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "60%",
          backgroundPosition: "50% 5%",
          noGradient: true,
        },
      },
    ],
  },
  {
    id: 4,
    size: "400мл",
    name: "Максимум",
    description: "Максимальный объём для больших порций",
    price: 4.5,
    priceUnit: "₽",
    dimensions: {
      diameter: 90,
      height: 135,
    },
    variants: [
      {
        id: "400-v1",
        name: "Вариант 1",

        image: "/img/400.3.png",
        thumb: "/img/400.3.png",
        color: "#1E2235",
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "55%",
          backgroundPosition: "50% 82%",
          noGradient: true,
        },
      },
      {
        id: "400-v2",
        name: "Вариант 2",

        image: "/img/400.1.png",
        thumb: "/img/400.1.png",
        color: "#FFFFFF",
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "70%",
          backgroundPosition: "50% 50%",
          noGradient: true,
        },
      },
      {
        id: "400-v3",
        name: "Вариант 3",
        image: "/img/400.2.png",
        thumb: "/img/400.2.png",
        color: "#C4A77D",
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "40%",
          backgroundPosition: "50% 50%",
          noGradient: true,
        },
      },
      {
        id: "400-v4",
        name: "Вариант 4",
        image: "/img/400.4.png",
        thumb: "/img/400.4.png",
        color: "#E53935",
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "55%",
          backgroundPosition: "50% 30%",
          noGradient: true,
        },
      },
      {
        id: "400-v5",
        name: "Вариант 5",
        image: "/img/400.5.png",
        thumb: "/img/400.5.png",
        isPattern: true,
        customSize: {
          width: "120%",
          height: "125%",
          backgroundSize: "40%",
          backgroundPosition: "50% 40%",
          noGradient: true,
        },
      },
    ],
  },
];

export const HERO_STATS = [
  {
    value: "5",
    label: "Размеров",
  },
  {
    value: "100%",
    label: "Эко-материалы",
  },
  {
    value: "24/7",
    label: "Поддержка",
  },
  {
    value: "500+",
    label: "Клиентов",
  },
];
