export const PRODUCTS = [
  {
    id: 1,
    size: "180мл",
    name: "Эспрессо",
    description: "Идеально для эспрессо и ристретто",
    price: 2.5,
    priceUnit: "₽",
    dimensions: {
      diameter: 62,
      height: 65,
    },
    variants: [
      {
        id: "180-v1",
        name: "Белый",
        image: "/img/180.1.png",
        thumb: "/img/180.1.png",
        color: "#FFFFFF",
      },
      {
        id: "180-v2",
        name: "Крафт",
        image: "/img/180.2.png",
        thumb: "/img/180.2.png",
        color: "#C4A77D",
      },
      {
        id: "180-v3",
        name: "Чёрный",
        image: "/img/180.3.png",
        thumb: "/img/180.3.png",
        color: "#1E2235",
      },
    ],
  },
  {
    id: 2,
    size: "250мл",
    name: "Американо",
    description: "Классический размер для американо",
    price: 3.2,
    priceUnit: "₽",
    dimensions: {
      diameter: 80,
      height: 90,
    },
    variants: [
      {
        id: "250-v1",
        name: "Вариант 1",
        image: "/img/250.1.jpg",
        thumb: "/img/250.1.jpg",
        color: "#FFFFFF",
      },
      {
        id: "250-v2",
        name: "Вариант 2",
        image: "/img/250.2.jpg",
        thumb: "/img/250.2.jpg",
        color: "#C4A77D",
      },
      {
        id: "250-v3",
        name: "Вариант 3",
        image: "/img/250.3.jpg",
        thumb: "/img/250.3.jpg",
        color: "#1E2235",
      },
      {
        id: "250-v4",
        name: "Вариант 4",
        image: "/img/250.4.jpg",
        thumb: "/img/250.4.jpg",
        color: "#1DB954",
      },
      {
        id: "250-v5",
        name: "Вариант 5",
        image: "/img/250.5.jpg",
        thumb: "/img/250.5.jpg",
        color: "#E53935",
      },
      {
        id: "250-v6",
        name: "Вариант 6",
        image: "/img/250.6.jpg",
        thumb: "/img/250.6.jpg",
        color: "#2196F3",
      },
      {
        id: "250-v7",
        name: "Вариант 7",
        image: "/img/250.7.jpg",
        thumb: "/img/250.7.jpg",
        color: "#9C27B0",
      },
      {
        id: "250-v8",
        name: "Вариант 8",
        image: "/img/250.8.jpg",
        thumb: "/img/250.8.jpg",
        isPattern: true,
      },
      {
        id: "250-v9",
        name: "Вариант 9",
        image: "/img/250.9.jpg",
        thumb: "/img/250.9.jpg",
        isPattern: true,
      },
      {
        id: "250-v10",
        name: "Вариант 10",
        image: "/img/250.10.jpg",
        thumb: "/img/250.10.jpg",
        isPattern: true,
      },
    ],
  },
  {
    id: 3,
    size: "350мл",
    name: "Латте",
    description: "Большой размер для латте и капучино",
    price: 3.8,
    priceUnit: "₽",
    dimensions: {
      diameter: 90,
      height: 110,
    },
    variants: [
      {
        id: "350-v1",
        name: "Вариант 1",
        image: "/img/350.1.png",
        thumb: "/img/350.1.png",
        color: "#FFFFFF",
      },
      {
        id: "350-v2",
        name: "Вариант 2",
        image: "/img/350.2.jpg",
        thumb: "/img/350.2.jpg",
        color: "#C4A77D",
      },
      {
        id: "350-v3",
        name: "Вариант 3",
        image: "/img/350.3.jpg",
        thumb: "/img/350.3.jpg",
        color: "#1E2235",
      },
      {
        id: "350-v4",
        name: "Вариант 4",
        image: "/img/350.4.png",
        thumb: "/img/350.4.png",
        isPattern: true,
      },
      {
        id: "350-v5",
        name: "Вариант 5",
        image: "/img/350.5.png",
        thumb: "/img/350.5.png",
        isPattern: true,
      },
      {
        id: "350-v6",
        name: "Вариант 6",
        image: "/img/350.6.jpg",
        thumb: "/img/350.6.jpg",
        isPattern: true,
      },
    ],
  },
  {
    id: 4,
    size: "400мл",
    name: "Максимум",
    description: "Максимальный объём для больших порций",
    price: 4.5,
    priceUnit: "₽",
    dimensions: {
      diameter: 90,
      height: 135,
    },
    variants: [
      {
        id: "400-v1",
        name: "Вариант 1",
        image: "/img/400.1.png",
        thumb: "/img/400.1.png",
        color: "#FFFFFF",
      },
      {
        id: "400-v2",
        name: "Вариант 2",
        image: "/img/400.2.png",
        thumb: "/img/400.2.png",
        color: "#C4A77D",
      },
      {
        id: "400-v3",
        name: "Вариант 3",
        image: "/img/400.3.jpg",
        thumb: "/img/400.3.jpg",
        color: "#1E2235",
      },
      {
        id: "400-v4",
        name: "Вариант 4",
        image: "/img/400.4.png",
        thumb: "/img/400.4.png",
        color: "#E53935",
      },
      {
        id: "400-v5",
        name: "Вариант 5",
        image: "/img/400.5.jpg",
        thumb: "/img/400.5.jpg",
        isPattern: true,
      },
    ],
  },
];

export const HERO_STATS = [
  {
    value: "4",
    label: "Размера",
  },
  {
    value: "100%",
    label: "Эко-материалы",
  },
  {
    value: "24/7",
    label: "Поддержка",
  },
  {
    value: "500+",
    label: "Клиентов",
  },
];
